version: '3.9'

x-node_image: &node_image
  image: node:16.1.0-alpine

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - $PWD/src:/var/www/html
      - $PWD/docker-images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tq-docker-template
    depends_on:
      - php

  php:
    build: $PWD/docker-images/php
    volumes:
      - $PWD/src:/var/www/html
    networks:
      - tq-docker-template

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - $PWD/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='Asia/Tokyo' --secure-file-priv="/docker-entrypoint-initdb.d"
    networks:
      - tq-docker-template

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - '3306:80'
    volumes:
      - /sessions
    networks:
      - tq-docker-template
    depends_on:
      - mysql

networks:
  tq-docker-template:
    external:
      name: tq-docker-template
